openapi: 3.0.1
info:
  title: Agent Executions OpenMetadata APIs API
  description: Common types and API definition for OpenMetadata
  contact:
    name: OpenMetadata
    url: https://open-metadata.org
    email: openmetadata-dev@googlegroups.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: '1.13'
servers:
- url: /api
  description: Current Host
- url: http://localhost:8585/api
  description: Endpoint URL
security:
- BearerAuth: []
tags:
- name: OpenMetadata APIs
paths:
  /:
    get:
      operationId: getIndex
      responses:
        default:
          description: default response
          content:
            text/html: {}
      tags:
      - OpenMetadata APIs
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
